name: Nova Build Wheels (macOS arm64)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .ci/**/*
      - .github/workflows/build-wheels-macos-arm64.yml
      - pyproject.toml
      - setup.py
  push:
    tags:
      - release/*
      # NOTE: Binary build pipelines should only get triggered on release candidate builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
      - ciflow/binaries/*
  release:
    types: [published]

jobs:
  generate-matrix:
    name: Generate macOS matrix
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@release/2.12
    with:
      package-type: wheel
      os: macos-arm64
      test-infra-repository: pytorch/test-infra
      test-infra-ref: release/2.12
      with-cuda: disabled
      with-rocm: disabled
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'

  build:
    name: Build macOS wheels
    needs: generate-matrix
    permissions:
      id-token: write
      contents: read
    uses: pytorch/test-infra/.github/workflows/build_wheels_macos.yml@release/2.12
    with:
      repository: meta-pytorch/tokenizers
      ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.sha }}
      test-infra-repository: pytorch/test-infra
      test-infra-ref: release/2.12
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      trigger-event: ${{ github.event_name }}
      package-name: pytorch_tokenizers
      runner-type: macos-14-xlarge
      setup-miniconda: true
      delocate-wheel: false
      smoke-test-script: .ci/scripts/wheel/test_wheel.py
